-- =====================================================================
-- SUPERSEDED — DO NOT APPLY
-- =====================================================================
-- This file originally shipped a standalone `create or replace function
-- public.check_pipeline_health()` fixing the missing degraded-check branches
-- for discovery/publish-prices (reviewer Pass 11, REV-042).
--
-- Reviewer Pass 12 (REV-062, blocker) found that this file, INC-3's edit to
-- sql/phase5_monitoring.sql, and sql/dedup_watchlist_health_check.sql each
-- committed a full, mutually incompatible `check_pipeline_health()` body —
-- no apply order produced a correct function; applying any one silently
-- reverted whatever the other two added.
--
-- Fix (2026-07-28, tech-lead): the three bodies have been reconciled into a
-- single authoritative function that carries INC-3's kill-switch pause-check
-- + resume-baseline fix, THIS file's REV-042 degraded-check branches, and
-- REV-047's ET/IST dedup, all together. That reconciled function now lives
-- SOLELY in sql/phase5_monitoring.sql (see its header note dated 2026-07-28).
--
-- This file no longer defines `check_pipeline_health()` — it is intentionally
-- left as a non-applyable historical marker so it can't be pasted/applied and
-- silently regress the reconciled function again. git history
-- (`git log -p -- sql/fix_missing_degraded_checks.sql`) retains the original
-- REV-042 body and its full rationale for reproducibility.
--
-- Apply sql/phase5_monitoring.sql only. See docs/runbook.md §2.3 for the
-- current apply order.
-- =====================================================================
